name: Core
on:
  - push
  - pull_request

jobs:
  lint:
    name: Lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node:
          - 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        name: Set up node
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://npm.pkg.github.com
      - name: Get NPM cache dir
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - name: Cache NPM
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-${{ matrix.node }}-
      - name: Install NPM^7.11
        run: npm install -g npm@^7.11.2 --no-fund --no-audit
#      - name: Output NPM version
#        id: npm-version
#        run: |
#          echo "::set-output name=version::$(npm -v)"
#      - name: Install NPM7
#        if: ${{ !startsWith(npm-version.version, '7' }}
#        run: npm install -g npm@^7.7.6
      - name: Install deps
        run: npm ci --no-fund
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Lint
        run: npm run lint
  test:
    runs-on: ${{ matrix.os }}
    name: Test ${{ matrix.os }}/Node ${{ matrix.node }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
        node:
          - 15
          - 14
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        name: Set up node
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://npm.pkg.github.com
      - name: Get NPM cache dir
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - name: Cache NPM
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-${{ matrix.node }}-
      - name: Install NPM^7.11
        run: npm install -g npm@^7.11.2 --no-fund --no-audit
      #      - name: Output NPM version
      #        id: npm-version
      #        run: |
      #          echo "::set-output name=version::$(npm -v)"
      #      - name: Install NPM7
      #        if: ${{ !startsWith(npm-version.version, '7' }}
      #        run: npm install -g npm@^7.7.6
      - name: Install deps
        run: npm ci --no-fund
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        run: npm run test -- --forbid-only --forbid-pending
      - name: Upload coverage
        if: ${{ matrix.os != 'windows-latest' }}
        continue-on-error: true
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: node-${{ matrix.node }}-on-${{ matrix.os }}-${{ github.event_name }}
          parallel: true
  posttest:
    runs-on: ubuntu-latest
    needs: test
    continue-on-error: true
    steps:
      - name: Finalise coverage report
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
  release:
    name: Release
    runs-on: ${{ matrix.os }}
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    needs:
      - lint
      - test
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node:
          - 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1000
          token: ${{ secrets.RELEASE_TOKEN }}
      - uses: actions/setup-node@v2
        name: Set up node
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://npm.pkg.github.com
      - name: Get NPM cache dir
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - name: Cache NPM
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-${{ matrix.node }}-
      - name: Install NPM^7.11
        run: npm install -g npm@^7.11.2 --no-fund --no-audit
      #      - name: Output NPM version
      #        id: npm-version
      #        run: |
      #          echo "::set-output name=version::$(npm -v)"
      #      - name: Install NPM7
      #        if: ${{ !startsWith(npm-version.version, '7' }}
      #        run: npm install -g npm@^7.7.6
      - name: Install deps
        run: npm ci --no-fund --no-audit
        env:
          NODE_AUTH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      - name: Release
        run: npm run release
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          NPM_TOKEN: ${{ secrets.RELEASE_TOKEN }}
